backend:
  image:
    repository: ghcr.io/davidc-dev/demo-app-backend
    tag: 1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
  envSecret:
    name: device-workflow-secrets
    tokenKey: GITHUB_TOKEN
    usernameKey: GITHUB_USERNAME
  resources: {}
  replicas: 1

frontend:
  image:
    repository: ghcr.io/davidc-dev/demo-app-frontend
    tag: 1.2
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  config:
    apiBaseUrl: "http://node-red-device-workflow-backend.device-apps.svc.cluster.local"
  resources: {}
  replicas: 1

route:
  enabled: true
  host: ""
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  annotations: {}
