backend:
  image:
    repository: ghcr.io/davidc-dev/demo-app-backend
    tag: 1.4
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
  envSecret:
    name: device-workflow-secrets
    tokenKey: GITHUB_TOKEN
    usernameKey: GITHUB_USERNAME
    argocdUrlKey: ARGOCD_URL
    argocdTokenKey: ARGOCD_TOKEN
    argocdDisableTlsKey: ARGOCD_DISABLE_TLS
  appsDomain: "demo.dcdevlab.net"
  resources: {}
  replicas: 1


frontend:
  image:
    repository: ghcr.io/davidc-dev/demo-app-frontend
    tag: 1.12
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  config:
    argocdUrl: "https://openshift-gitops-server-openshift-gitops.apps.demo.dcdevlab.net"
    devSpacesUrl: "https://devspaces.apps.demo.dcdevlab.net/"
  resources: {}
  replicas: 1

route:
  enabled: true
  host: ""
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  annotations: {}
